#!/bin/bash
#SBATCH -A cc3uv3p # 2017 XSEDE Applications of Parallel Computing Course Allocation
#SBATCH -J auto-particle-gpu
#SBATCH -o auto-particle-gpu.stdout
#SBATCH -p GPU-shared
#SBATCH --gres=gpu:k80:1
#SBATCH -t 00:10:00
#SBATCH -N 1         

./gpu -n 500 
./gpu -n 1000 
./gpu -n 2000 
./gpu -n 4000 
./gpu -n 8000 
./serial -n 500 
./serial -n 1000 
./serial -n 2000 
./serial -n 4000 
./serial -n 8000  



assign_bins_gpu <<< blks, NUM_THREADS >>> (d_particles, d_bins, d_counts, n, bs);
clear_accel_gpu <<< blks, NUM_THREADS >>> (d_particles, n);
int bin_blks = (bs*bs + NUM_THREADS -1) / NUM_THREADS;
compute_forces_bin_gpu <<< bin_blks, NUM_THREADS >>> (d_particles, bs, d_bins,
d_counts);
move_gpu <<< blks, NUM_THREADS >>> (d_particles, n, size);
